[package]
name = "vacro"
version = "0.1.1"
edition = "2021"
authors = ["FeVeR renyis@foxmail.com"]
license = "MIT OR Apache-2.0"

description = "A declarative parsing library for Rust procedural macros, simplifying input handling."
repository = "https://github.com/FeVeR-Store/vacro"
readme = "readme.md"
keywords = ["macros", "parsing", "syn", "proc-macro"]
categories = ["development-tools::procedural-macro-helpers", "parsing"]

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[features]
extra-traits = ["syn/extra-traits"]

[dev-dependencies]
trybuild = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }

[dependencies]
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
