[package]
name = "vacro"
version = "0.1.0"
edition = "2024"
authors = ["FeVeR renyis@foxmail.com"]

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[features]
default = []
report = ["dep:vacro-report"]
extra-traits = ["syn/extra-traits"]

[workspace]
members = ["vacro-report", "vacro-report-macro"]

[dev-dependencies]
trybuild = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }

[dependencies]
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
vacro-report = { path = "./vacro-report", optional = true }
