[package]
name = "vacro-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
similar = "2.7.0"
thiserror = "2.0"
vacro-trace = { path = "../vacro-trace", features = ["types"] }
